### ISSUE TITLE
Update libertem with logo from repository

### ISSUE THREAD

**Issue by lancewilson-monash** [Characterisation-Virtual-Laboratory/CharacterisationVL-Software#46]
https://github.com/LiberTEM/LiberTEM/tree/master/corporatedesign/logo

**Comment by lancewilson-monash** [comment]
SVG file added to repository

**Comment by sk1p** [comment]
Hi, thanks for taking action on this :grin: It appears, though, that something went wrong when adding the icon:

https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software/blob/c0dfe6d665c9985beb04bd3912ba9309f7003b1a/xdg/xdg_data/icons/hicolor/48x48/apps/LiberTEM%20logo%20icon.svg

There is HTML in the file instead of SVG, which can happen if you directly download the a github link like this one:

https://github.com/LiberTEM/LiberTEM/blob/master/corporatedesign/logo/LiberTEM%20logo%20icon.svg

Instead, to get the SVG, you need to press the little "raw" icon to get a link like this:

https://raw.githubusercontent.com/LiberTEM/LiberTEM/master/corporatedesign/logo/LiberTEM%20logo%20icon.svg

**Comment by lancewilson-monash** [comment]
@ozej8y Did you replace the image?

**Comment by ozej8y** [comment]
I don't remember this post. I'll check it out and make sure the icon is correct.

**Comment by ozej8y** [comment]
I've pulled the icon logo in and updated the menu files to reference it.
